CREATE TABLE `monitor_tracer` (
  `id` varchar(64) NOT NULL DEFAULT '0' COMMENT '主键ID',
  `create_time` timestamp(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `server_name` varchar(128) DEFAULT NULL COMMENT '服务名',
  `operation_name` varchar(255) DEFAULT NULL COMMENT '操作名',
  `span_id` varchar(64) DEFAULT NULL COMMENT 'spanId',
  `trace_id` varchar(64) DEFAULT NULL COMMENT 'traceId',
  `parent_id` varchar(64) DEFAULT NULL COMMENT '父的spanId',
  `server_instance_id` varchar(64) DEFAULT NULL COMMENT '服务实例ID',
  `component` varchar(255) DEFAULT NULL COMMENT '组件',
  `arguments` LONGTEXT DEFAULT NULL COMMENT '参数',
  `start_time` datetime(3) DEFAULT NULL COMMENT '执行开始时间',
  `finish_time` datetime(3) DEFAULT NULL COMMENT '执行结束时间',
  `cost_time` int(11) DEFAULT NULL COMMENT '执行时长：毫秒',
  `tags` LONGTEXT DEFAULT NULL COMMENT '标签json串',
  `error` bit DEFAULT NULL COMMENT '是否异常',
  `error_message` LONGTEXT DEFAULT NULL COMMENT '异常信息',
  `error_stack` LONGTEXT DEFAULT NULL COMMENT '异常堆栈信息',
  `user_id` varchar(64) DEFAULT NULL COMMENT 'Session里面的用户ID',
  `reference_type` int(11) DEFAULT NULL COMMENT '依赖类型：0 父子，1 跟随',
  `hostname` varchar(64) DEFAULT NULL COMMENT '主机名',
  `ip` varchar(32) DEFAULT NULL COMMENT 'ip',
  `seq` int(11) DEFAULT NULL COMMENT '排序',
  PRIMARY KEY (`id`) ,
  KEY `idx_server_name` (`server_name`) ,
  KEY `idx_operation_name` (`operation_name`) ,
  KEY `idx_trace_id` (`trace_id`) ,
  KEY `idx_create_time` (`create_time`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;